apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - CSIDriver.yaml
  - DaemonSet.yaml
  - Deployment.yaml
  - StorageClass.yaml

images:
  - name: quay.io/minio/directpv
    digest: sha256:76bb7e4d204f95fea9e05637f18b68de2e54543ed0e2f3c4eae330d72b304abb

  - name: quay.io/minio/csi-node-driver-registrar
    digest: sha256:c571b1462c6798725c0da58aab4896f910b38dc4ef48352ead3e4625d2d63a06

  - name: quay.io/minio/livenessprobe
    digest: sha256:8f3b1bec9c87a832a3fe6e8b7f165e0ff048aef7373f9764f40efee456a00321

  - name: quay.io/minio/csi-provisioner
    digest: sha256:fff8927753ef1a67278804897de5dda9fd47c48b27575d53daafb12ab7179446

  - name: quay.io/minio/csi-resizer
    digest: sha256:0640655cdf10b17bf50b304d5c3555135141b6bd3d79260a3ce389bf90d4e4bf
