#HELM+# {{ with .Values.controller }}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    directpv.min.io/image-tag: v5.1.0
    #HELM+# {{- with $.Values.annotations }}
    #HELM+# {{- . | toYaml | nindent 4 }}
    #HELM+# {{- end }}
  labels:
    application-name: directpv.min.io
    application-type: CSIDriver
    directpv.min.io/created-by: kubectl-directpv
    directpv.min.io/version: v1beta1
    #HELM+# {{- with $.Values.labels }}
    #HELM+# {{- . | toYaml | nindent 4 }}
    #HELM+# {{- end }}
  name: controller
  namespace: directpv
spec:
  replicas: 3 #HELM-#
  #HELM+# replicas: {{ .replicas }}
  selector:
    matchLabels:
      selector.directpv.min.io: controller-controller
      #HELM+# {{- with .podLabels }}
      #HELM+# {{ . | toYaml | nindent 6 }}
      #HELM+# {{- end }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        created-by: kubectl-directpv
        #HELM+# {{- with .podAnnotations }}
        #HELM+# {{ . | toYaml | nindent 8 }}
        #HELM+# {{- end }}
      labels:
        selector.directpv.min.io: controller-controller
        #HELM+# {{- with .podLabels }}
        #HELM+# {{ . | toYaml | nindent 8 }}
        #HELM+# {{- end }}
      name: controller
      namespace: directpv
    spec:
      #HELM+# {{- if $.Values.controller.hostNetwork }}
      #HELM+# hostNetwork: true
      #HELM+# dnsPolicy: ClusterFirstWithHostNet
      #HELM+# {{- end }}
      containers:
      - args:
        - --v=3
        - --timeout=300s
        - --csi-address=$(CSI_ENDPOINT)
        - --leader-election
        - --feature-gates=Topology=true
        - --strict-topology
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: quay.io/minio/csi-provisioner@sha256:fff8927753ef1a67278804897de5dda9fd47c48b27575d53daafb12ab7179446 #HELM-#
        #HELM+# image: {{ include "directpv.resolveImage" (dict "name" "csiProvisioner" "root" $) }}
        #HELM+# imagePullPolicy: {{ $.Values.images.pullPolicy }}
        name: csi-provisioner
        securityContext:
          privileged: true
        terminationMessagePath: /var/log/controller-provisioner-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          mountPropagation: None
          name: socket-dir
      - args:
        - --v=3
        - --timeout=300s
        - --csi-address=$(CSI_ENDPOINT)
        - --leader-election
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: quay.io/minio/csi-resizer@sha256:0640655cdf10b17bf50b304d5c3555135141b6bd3d79260a3ce389bf90d4e4bf #HELM-#
        #HELM+# image: {{ include "directpv.resolveImage" (dict "name" "csiResizer" "root" $) }}
        #HELM+# imagePullPolicy: {{ $.Values.images.pullPolicy }}
        name: csi-resizer
        securityContext:
          privileged: true
          #HELM+# {{ with .podSecurityContext }}
          #HELM+# {{ . | toYaml | nindent 10 }}
          #HELM+# {{ end }}
        terminationMessagePath: /var/log/controller-csi-resizer-termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /csi
          mountPropagation: None
          name: socket-dir
      - args:
        - controller
        - --identity=directpv-min-io
        - -v=3
        - --csi-endpoint=$(CSI_ENDPOINT)
        - --kube-node-name=$(KUBE_NODE_NAME)
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: quay.io/minio/directpv@sha256:76bb7e4d204f95fea9e05637f18b68de2e54543ed0e2f3c4eae330d72b304abb #HELM-#
        #HELM+# image: {{ include "directpv.resolveImage" (dict "name" "directpv" "root" $) }}
        #HELM+# imagePullPolicy: {{ $.Values.images.pullPolicy }}
        name: controller
        ports:
        - containerPort: 9898
          name: healthz
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          mountPropagation: None
          name: socket-dir
      #HELM+# {{- with $.Values.images.pullSecrets }}
      #HELM+# imagePullSecrets: {{ . }}
      #HELM+# {{- end }}
      serviceAccountName: directpv-min-io
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/controller-controller #HELM-#
          #HELM+# path: {{ (include "directpv.kubeletDirPath" $) }}/plugins/controller-controller
          type: DirectoryOrCreate
        name: socket-dir
#HELM+# {{ end }}
