apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - CSIDriver.yaml
  - DaemonSet.yaml
  - Deployment.yaml
  - directpvinitrequests.directpv.min.io.yaml
  - directpvnodes.directpv.min.io.yaml
  - directpvvolumes.directpv.min.io.yaml
  - RoleBinding.yaml
  - Role.yaml
  - StorageClass.yaml

images:
  - name: quay.io/minio/directpv
    newTag: v5.0.2

  - name: quay.io/minio/csi-node-driver-registrar
    digest: sha256:8f00013a19bd3bea021f3e96b093814fb110b383c0fd050d2a5309afb0ed0ccb

  - name: quay.io/minio/livenessprobe
    digest: sha256:d8f7d431a2a148970dcb337f24b265d173bcee58bbeeae9af7ae60f01ce49be2

  - name: quay.io/minio/csi-provisioner
    digest: sha256:24816a743663d153060f0c3fc30005f05bea23c8b0fd2551fd667042741e8562

  - name: quay.io/minio/csi-resizer
    digest: sha256:fc0c1f9cbc0ebb16283c0e425c031041eedb0e8ebbe6a1adec3de41584548ce6

patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v5.0.2
    target:
      kind: Deployment
      name: controller
  - patch: |-
      - op: replace
        path: /metadata/annotations/directpv.min.io~1image-tag
        value: v5.0.2
    target:
      kind: DaemonSet
      name: node-server
