apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - privileged-rolebinding.yaml

images:
  - name: quay.io/minio/csi-node-driver-registrar
    newName: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel8
    digest: sha256:a7bb01170545d879015a674ff2d8f1169e0a24da080efa53f6f2404e56373196

  - name: quay.io/minio/livenessprobe
    newName: registry.redhat.io/openshift4/ose-csi-livenessprobe-rhel8
    digest: sha256:a6aa576de2ba40e5aba7af4605cf5725efc262c99d3c584f14e0ad2c89c8fd2c

  - name: quay.io/minio/csi-provisioner
    newName: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel8
    digest: sha256:ffe69d56fe2137f8da357efd7712128b1b611ae5ce17cf342026874ad2588369

  - name: quay.io/minio/csi-resizer
    newName: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel8
    digest: sha256:9f73ff30445a500889b7f4d414b05cb558ae55aaf7161d387789857cd066af2f
