apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    aistor.min.io/authors: MinIO, Inc.
    aistor.min.io/license: Enterprise
    aistor.min.io/support: https://subnet.min.io
    aistor.min.io/version: RELEASE.2024-10-17T18-11-50Z
  name: loadbalancer-operator
  namespace: aistor
spec:
  replicas: 1
  selector:
    matchLabels:
      aistor.min.io/name: loadbalancer-operator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        aistor.min.io/authors: MinIO, Inc.
        aistor.min.io/license: Enterprise
        aistor.min.io/support: https://subnet.min.io
        aistor.min.io/version: RELEASE.2024-10-17T18-11-50Z
      labels:
        aistor.min.io/name: loadbalancer-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: aistor.min.io/name
                operator: In
                values:
                - loadbalancer-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - loadbalancer
        - -license
        - /tmp/license/minio.license
        env:
        - name: MINIO_OPERATOR_DEPLOYMENT_NAME
          value: loadbalancer-operator
        image: quay.io/minio/aistor/operator:RELEASE.2024-10-17T18-11-50Z
        imagePullPolicy: IfNotPresent
        name: controller
        resources:
          requests:
            cpu: 200m
            ephemeral-storage: 500Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp/license
          name: minio-license
      serviceAccountName: aistor
      volumes:
      - name: minio-license
        secret:
          defaultMode: 444
          optional: true
          secretName: minio-license
