apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-operator
  namespace: aistor
spec:
  replicas: 1
  selector:
    matchLabels:
      aistor.min.io/name: catalog-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aistor.min.io/name: catalog-operator
    spec:
      serviceAccountName: aistor
      containers:
        - name: controller
          image: registry.min.dev/aistor/operator:2024-09-18-00-29-42
          imagePullPolicy: IfNotPresent
          args:
            - catalog
            - -license
            - /tmp/license/minio.license
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
              ephemeral-storage: 500Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - "ALL"
            allowPrivilegeEscalation: false
          env:
            - name: MINIO_OPERATOR_DEPLOYMENT_NAME
              value: catalog-operator
          volumeMounts:
            - name: minio-license
              mountPath: /tmp/license
      volumes:
        - name: minio-license
          secret:
            defaultMode: 444
            secretName: minio-license
            optional: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: aistor.min.io/name
                    operator: In
                    values:
                      - catalog-operator
              topologyKey: kubernetes.io/hostname
